### ISSUE TITLE
Issue with animation-fill-mode: forwards;

### ISSUE THREAD

**Issue by justinmwarner** [jakob101/postcss-inline-rtl#17]
I have the following SCSS:
```scss
    .greyBar {
        background-color: grey;
        animation: revealAnimation 2s linear;
        animation-fill-mode: forwards;
    }
    @keyframes revealAnimation {
        to {
            width: 0px;
            margin-left: 150px;
        }
    }
```

This works without the postcss-inline-rtl. 

However, once added, it compiles down to 
![image](https://user-images.githubusercontent.com/2288818/35402892-c569ca0e-01b2-11e8-9b99-571c0c45666f.png)

You'll see that animation-fill-mode is now initial.

I see two problems here though.

1. The animation-fill-mode is getting changed incorrectly.
2. The loader does't have any way to skip items. And I think this could be argued, but it would be nice to have an option to use the ignore autoprefixer tag. https://github.com/postcss/autoprefixer#control-comments
