### ISSUE TITLE
Property order matters

### ISSUE THREAD

**Issue by chrisjshull** [jakob101/postcss-inline-rtl#7]
One of the examples in the readme actually demonstrates a bug:

``` css
/*  Edge case (cancelling LTR/RTL values) */
.class {
  border-left: 10px;
  border: none; /*  Notice this doesn't change LTR-RTL */
}

/*  converts to: */
html[dir] .class {
  border: none;
}
html[dir='ltr'] .class {
  border-left: 10px;
}
html[dir='rtl'] .class {
  border-right: 10px;
}
```

The resulting CSS doesn't have the same effect as the original CSS.
Demo: https://github.com/jakob101/postcss-inline-rtl

The resulting CSS should be:

``` css
html[dir='ltr'] .class {
  border-left: 10px;
}
html[dir='rtl'] .class {
  border-right: 10px;
}
html[dir] .class {
  border: none;
}
```
